//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Web_Polimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Permiso
    {
        public int idRolPermiso { get; set; }
        public int idRol { get; set; }
        public int idPermiso { get; set; }
    }
}
